version: '3'

services:
  database:
    image: postgres
    environment:
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_mihmo
    ports:
      - "5432:5432"
    restart: always